import { describe, expect, it } from 'vitest';
import { translateSql, reorderParameters } from '../src/sql/translator.js';

const opts = {
  uppercaseIdentifiers: true,
  informationSchemaRewrite: true,
  pgCatalogCompat: true,
  allowMultiStatement: false,
  maxRows: 0,
};

describe('SQL translation', () => {
  it('converts LIMIT/OFFSET', () => {
    expect(translateSql('select * from mylib.orders limit 10 offset 20', opts).sql)
      .toBe('SELECT * FROM MYLIB.ORDERS OFFSET 20 ROWS FETCH FIRST 10 ROWS ONLY');
  });
  it('converts positional parameters', () => {
    const t = translateSql('select * from t where b=$2 and a=$1', opts);
    expect(t.sql).toContain('B=?');
    expect(reorderParameters(['A','B'], t.parameterOrder)).toEqual(['B','A']);
  });
  it('rewrites information_schema', () => {
    expect(translateSql('select * from information_schema.tables', opts).sql).toContain('SYSIBM.TABLES');
  });

  it('adds SYSIBM.SYSDUMMY1 for PostgreSQL scalar SELECT without FROM', () => {
    expect(translateSql('select now() as ts', opts).sql)
      .toBe('SELECT CURRENT TIMESTAMP AS TS FROM SYSIBM.SYSDUMMY1');
  });

  it('inserts SYSIBM.SYSDUMMY1 before WHERE/GROUP/HAVING clauses', () => {
    expect(translateSql('select 1 as ok where 1=1', opts).sql)
      .toBe('SELECT 1 AS OK FROM SYSIBM.SYSDUMMY1 WHERE 1=1');
    expect(translateSql('select count(*) as c group by 1 having count(*) > 0', opts).sql)
      .toMatch(/^SELECT COUNT\(\*\) AS C FROM SYSIBM\.SYSDUMMY1 GROUP BY 1 HAVING COUNT\(\*\) > 0$/i);
  });
  it('rejects multiple statements', () => {
    expect(() => translateSql('select 1; delete from x', opts)).toThrow(/Multiple SQL/);
  });
});

describe('PostgreSQL DDL compatibility', () => {
  it('maps PostgreSQL SERIAL pseudo-types to Db2 for i identity columns', () => {
    const sql = translateSql(
      'create table monai.serial_test (id serial primary key, serial integer, note varchar(20))',
      opts,
    ).sql;
    expect(sql).toContain('ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
    expect(sql).toContain('SERIAL INTEGER');
    expect(translateSql('create table monai.small_serial_test (id smallserial)', opts).sql)
      .toContain('ID SMALLINT GENERATED BY DEFAULT AS IDENTITY');
    expect(translateSql('create table monai.big_serial_test (id bigserial)', opts).sql)
      .toContain('ID BIGINT GENERATED BY DEFAULT AS IDENTITY');
  });

  it('rejects multiple SERIAL columns because Db2 for i permits one identity column per table', () => {
    expect(() => translateSql('create table monai.t (a serial, b serial)', opts))
      .toThrow(/only one identity column/i);
  });

  it('maps SERIAL when adding a new column', () => {
    expect(translateSql('alter table monai.t add column id serial', opts).sql)
      .toContain('ADD COLUMN ID INTEGER GENERATED BY DEFAULT AS IDENTITY');
  });

  it('rewrites a top-level PostgreSQL EXISTS select into a Db2 predicate expression', () => {
    const sql = translateSql(
      "select exists(select 1 from information_schema.tables where table_schema='MONAI') as present",
      opts,
    ).sql;
    expect(sql).toContain('CASE WHEN EXISTS (SELECT 1 FROM SYSIBM.TABLES');
    expect(sql).toContain('THEN 1 ELSE 0 END AS PRESENT FROM SYSIBM.SYSDUMMY1');
  });

  it('maps ContextForge PostgreSQL DDL types to Db2 for i persistent types', () => {
    const sql = translateSql(
      `create table gateways (
        id varchar(36) not null,
        name varchar not null,
        capabilities json not null,
        auth_value jsonb,
        description text,
        binary_content bytea,
        created_at timestamp with time zone not null,
        last_seen timestamp without time zone,
        local_time time without time zone,
        PRIMARY KEY (id),
        UNIQUE (name)
      )`,
      opts,
    ).sql;
    expect(sql).toContain('ID VARCHAR(36) NOT NULL');
    expect(sql).toContain('NAME VARCHAR(1024) NOT NULL');
    expect(sql).toContain('CAPABILITIES CLOB(2G) CCSID 1208 NOT NULL');
    expect(sql).toContain('AUTH_VALUE CLOB(2G) CCSID 1208');
    expect(sql).toContain('DESCRIPTION CLOB(2G) CCSID 1208');
    expect(sql).toContain('BINARY_CONTENT BLOB(2G)');
    expect(sql).toContain('CREATED_AT TIMESTAMP NOT NULL');
    expect(sql).toContain('LAST_SEEN TIMESTAMP');
    expect(sql).not.toContain('TIMESTAMP WITHOUT TIME ZONE');
    expect(sql).toContain('LOCAL_TIME TIME');
    expect(sql).not.toContain('TIME WITHOUT TIME ZONE');
  });

  it('uses the configured length only for PostgreSQL VARCHAR without a length', () => {
    const sql = translateSql('create table t (a varchar, b varchar(36))', {
      ...opts,
      ddlDefaultVarcharLength: 2048,
    }).sql;
    expect(sql).toContain('A VARCHAR(2048)');
    expect(sql).toContain('B VARCHAR(36)');
  });

});
