import { classify } from './classifier.js';

export interface Translation {
  original: string;
  sql: string;
  kind: ReturnType<typeof classify>;
  parameterOrder: number[];
}

export interface TranslateOptions {
  uppercaseIdentifiers: boolean;
  informationSchemaRewrite: boolean;
  pgCatalogCompat: boolean;
  allowMultiStatement: boolean;
  maxRows: number;
  ddlDefaultVarcharLength?: number;
}

export function translateSql(input: string, options: TranslateOptions): Translation {
  let sql = input.trim();
  if (!options.allowMultiStatement && hasMultipleStatements(sql)) {
    throw Object.assign(new Error('Multiple SQL statements in one PostgreSQL Query message are disabled'), { sqlstate: '0A000' });
  }
  sql = sql.replace(/;+\s*$/, '');

  const parameterOrder: number[] = [];
  sql = sql.replace(/\$(\d+)/g, (_m, n) => {
    parameterOrder.push(Number(n));
    return '?';
  });

  sql = rewritePgCasts(sql);
  sql = rewritePgSerialTypes(sql);
  sql = rewritePgDdlTypes(sql, options.ddlDefaultVarcharLength ?? 1024);
  sql = rewriteTopLevelExists(sql);
  sql = rewriteLimitOffset(sql);
  sql = rewritePgFunctions(sql);
  sql = ensureDb2SelectSource(sql);

  if (options.informationSchemaRewrite) sql = rewriteInformationSchema(sql);
  if (options.pgCatalogCompat) sql = rewritePgCatalog(sql);

  if (options.uppercaseIdentifiers) sql = uppercaseUnquotedRelationIdentifiers(sql);
  if (options.maxRows > 0 && /^\s*select\b/i.test(sql) && !/\bfetch\s+(first|next)\b/i.test(sql)) {
    sql = `${sql} FETCH FIRST ${Math.trunc(options.maxRows)} ROWS ONLY`;
  }

  return { original: input, sql, kind: classify(sql), parameterOrder };
}

export function reorderParameters(values: unknown[], order: number[]): unknown[] {
  if (!order.length) return values;
  return order.map((oneBased) => values[oneBased - 1] ?? null);
}

function rewritePgCasts(sql: string): string {
  // Conservative common-case conversion. Complex expressions should use CAST explicitly.
  return sql.replace(
    /((?:'[^']*(?:''[^']*)*'|\$\d+|\?|[A-Za-z_][A-Za-z0-9_.]*|\d+(?:\.\d+)?))::([A-Za-z_][A-Za-z0-9_ ]*(?:\([^)]*\))?)/g,
    'CAST($1 AS $2)',
  );
}

function rewritePgSerialTypes(sql: string): string {
  if (/^\s*create\s+(?:(?:global|local)\s+temporary\s+|temporary\s+|temp\s+|unlogged\s+)?table\b/i.test(sql)) {
    const open = firstUnquotedChar(sql, '(');
    if (open < 0) return sql;
    const close = matchingParen(sql, open);
    if (close < 0) return sql;
    const body = sql.slice(open + 1, close);
    const definitions = splitDefinitionList(body);
    const serialColumns = definitions.filter(isSerialColumnDefinition).length;
    if (serialColumns > 1) {
      throw Object.assign(
        new Error('Db2 for i supports only one identity column per table; CREATE TABLE contains multiple PostgreSQL SERIAL columns'),
        { sqlstate: '0A000' },
      );
    }
    const rewritten = definitions.map(rewriteSerialColumnDefinition).join(',');
    return `${sql.slice(0, open + 1)}${rewritten}${sql.slice(close)}`;
  }

  if (/^\s*alter\s+table\b/i.test(sql)) {
    // PostgreSQL ALTER TABLE ... ADD [COLUMN] name SERIAL.  This conservative
    // form deliberately does not rewrite a column literally named SERIAL.
    return sql.replace(
      /(\bADD\s+(?:COLUMN\s+)?(?:"(?:[^"]|"")*"|[A-Za-z_][A-Za-z0-9_$#@]*)\s+)(SMALLSERIAL|SERIAL2|SERIAL4|SERIAL8|BIGSERIAL|SERIAL)\b/gi,
      (_m, prefix: string, serialType: string) => `${prefix}${serialReplacement(serialType)}`,
    );
  }
  return sql;
}

function isSerialColumnDefinition(definition: string): boolean {
  if (/^\s*(?:CONSTRAINT|PRIMARY|UNIQUE|FOREIGN|CHECK|EXCLUDE)\b/i.test(definition)) return false;
  return /^\s*(?:"(?:[^"]|"")*"|[A-Za-z_][A-Za-z0-9_$#@]*)\s+(?:SMALLSERIAL|SERIAL2|SERIAL4|SERIAL8|BIGSERIAL|SERIAL)\b/i.test(definition);
}

function rewriteSerialColumnDefinition(definition: string): string {
  if (/^\s*(?:CONSTRAINT|PRIMARY|UNIQUE|FOREIGN|CHECK|EXCLUDE)\b/i.test(definition)) return definition;
  return definition.replace(
    /^(\s*(?:"(?:[^"]|"")*"|[A-Za-z_][A-Za-z0-9_$#@]*)\s+)(SMALLSERIAL|SERIAL2|SERIAL4|SERIAL8|BIGSERIAL|SERIAL)\b/i,
    (_m, prefix: string, serialType: string) => `${prefix}${serialReplacement(serialType)}`,
  );
}

function serialReplacement(type: string): string {
  switch (type.toUpperCase()) {
    case 'SMALLSERIAL':
    case 'SERIAL2':
      return 'SMALLINT GENERATED BY DEFAULT AS IDENTITY';
    case 'BIGSERIAL':
    case 'SERIAL8':
      return 'BIGINT GENERATED BY DEFAULT AS IDENTITY';
    case 'SERIAL':
    case 'SERIAL4':
    default:
      return 'INTEGER GENERATED BY DEFAULT AS IDENTITY';
  }
}


/**
 * Translate PostgreSQL DDL-only data types into persistent Db2 for i types.
 *
 * SQLAlchemy's PostgreSQL compiler deliberately emits several types which are
 * either incomplete or PostgreSQL-specific from Db2 for i's point of view:
 *   String()              -> VARCHAR            (no length)
 *   JSON / JSONB          -> PostgreSQL JSON types
 *   Text()                -> TEXT
 *   LargeBinary()         -> BYTEA
 *   DateTime(timezone=1)  -> TIMESTAMP WITH TIME ZONE
 *   DateTime()            -> TIMESTAMP WITHOUT TIME ZONE
 *
 * Db2 for i requires an explicit VARCHAR length and has no native JSON data
 * type.  Keep this rewrite scoped to CREATE/ALTER TABLE so normal expressions,
 * casts and pg_catalog compatibility SQL are not changed accidentally.
 */
function rewritePgDdlTypes(sql: string, defaultVarcharLength: number): string {
  if (/^\s*create\s+(?:(?:global|local)\s+temporary\s+|temporary\s+|temp\s+|unlogged\s+)?table\b/i.test(sql)) {
    const open = firstUnquotedChar(sql, '(');
    if (open < 0) return sql;
    const close = matchingParen(sql, open);
    if (close < 0) return sql;
    const body = sql.slice(open + 1, close);
    const rewritten = splitDefinitionList(body).map((definition) => rewriteDb2ColumnTypeDefinition(definition, defaultVarcharLength)).join(',');
    return `${sql.slice(0, open + 1)}${rewritten}${sql.slice(close)}`;
  }

  if (/^\s*alter\s+table\b/i.test(sql)) {
    // ALTER TABLE ... ADD [COLUMN] <name> <type> ... is the DDL form used by
    // Alembic for new columns.  Rewrite the type part while leaving all other
    // ALTER actions untouched.
    return sql.replace(
      /(\bADD\s+(?:COLUMN\s+)?(?:"(?:[^"]|"")*"|[A-Za-z_][A-Za-z0-9_$#@]*)\s+)([^,]+)$/i,
      (_m, prefix: string, rest: string) => `${prefix}${rewriteDb2TypePrefix(rest, defaultVarcharLength)}`,
    );
  }
  return sql;
}

function rewriteDb2ColumnTypeDefinition(definition: string, defaultVarcharLength: number): string {
  if (/^\s*(?:CONSTRAINT|PRIMARY|UNIQUE|FOREIGN|CHECK|EXCLUDE)\b/i.test(definition)) return definition;
  return definition.replace(
    /^(\s*(?:"(?:[^"]|"")*"|[A-Za-z_][A-Za-z0-9_$#@]*)\s+)([\s\S]*)$/,
    (_m, prefix: string, rest: string) => `${prefix}${rewriteDb2TypePrefix(rest, defaultVarcharLength)}`,
  );
}

function rewriteDb2TypePrefix(rest: string, defaultVarcharLength: number): string {
  let value = rest;

  // Order matters: rewrite the longest PostgreSQL type spellings first.
  value = value.replace(/^TIMESTAMP\s+(?:WITH|WITHOUT)\s+TIME\s+ZONE\b/i, 'TIMESTAMP');
  value = value.replace(/^TIME\s+(?:WITH|WITHOUT)\s+TIME\s+ZONE\b/i, 'TIME');
  value = value.replace(/^DOUBLE\s+PRECISION\b/i, 'DOUBLE');
  value = value.replace(/^BYTEA\b/i, 'BLOB(2G)');
  value = value.replace(/^JSONB?\b/i, 'CLOB(2G) CCSID 1208');
  value = value.replace(/^TEXT\b/i, 'CLOB(2G) CCSID 1208');

  // PostgreSQL permits VARCHAR with no maximum length; Db2 for i requires a
  // length attribute.  1024 is intentionally conservative enough for indexed
  // ContextForge identifiers while still covering names, URLs and session IDs.
  const varcharLength = Math.max(1, Math.min(32740, Math.trunc(defaultVarcharLength)));
  value = value.replace(/^VARCHAR\b(?!\s*\()/i, `VARCHAR(${varcharLength})`);
  value = value.replace(/^CHARACTER\s+VARYING\b(?!\s*\()/i, `VARCHAR(${varcharLength})`);

  return value;
}

function rewriteTopLevelExists(sql: string): string {
  const match = /^\s*select\s+exists\s*\(/i.exec(sql);
  if (!match) return sql;
  const open = sql.indexOf('(', match.index);
  if (open < 0) return sql;
  const close = matchingParen(sql, open);
  if (close < 0) return sql;
  const subquery = sql.slice(open + 1, close);
  const tail = sql.slice(close + 1);
  // Db2 for i supports EXISTS as a predicate, not as a bare SELECT-list item.
  // A searched CASE preserves PostgreSQL's scalar 0/1 truth semantics for
  // clients while keeping the subquery itself intact for normal translation.
  return `SELECT CASE WHEN EXISTS (${subquery}) THEN 1 ELSE 0 END${tail}`;
}

function firstUnquotedChar(sql: string, wanted: string): number {
  let inSingle = false;
  let inDouble = false;
  for (let i = 0; i < sql.length; i++) {
    const c = sql[i]!;
    if (c === "'" && !inDouble) {
      if (inSingle && sql[i + 1] === "'") { i++; continue; }
      inSingle = !inSingle;
      continue;
    }
    if (c === '"' && !inSingle) {
      if (inDouble && sql[i + 1] === '"') { i++; continue; }
      inDouble = !inDouble;
      continue;
    }
    if (!inSingle && !inDouble && c === wanted) return i;
  }
  return -1;
}

function matchingParen(sql: string, open: number): number {
  let depth = 0;
  let inSingle = false;
  let inDouble = false;
  for (let i = open; i < sql.length; i++) {
    const c = sql[i]!;
    if (c === "'" && !inDouble) {
      if (inSingle && sql[i + 1] === "'") { i++; continue; }
      inSingle = !inSingle;
      continue;
    }
    if (c === '"' && !inSingle) {
      if (inDouble && sql[i + 1] === '"') { i++; continue; }
      inDouble = !inDouble;
      continue;
    }
    if (inSingle || inDouble) continue;
    if (c === '(') depth++;
    else if (c === ')' && --depth === 0) return i;
  }
  return -1;
}

function splitDefinitionList(body: string): string[] {
  const parts: string[] = [];
  let start = 0;
  let depth = 0;
  let inSingle = false;
  let inDouble = false;
  for (let i = 0; i < body.length; i++) {
    const c = body[i]!;
    if (c === "'" && !inDouble) {
      if (inSingle && body[i + 1] === "'") { i++; continue; }
      inSingle = !inSingle;
      continue;
    }
    if (c === '"' && !inSingle) {
      if (inDouble && body[i + 1] === '"') { i++; continue; }
      inDouble = !inDouble;
      continue;
    }
    if (inSingle || inDouble) continue;
    if (c === '(') depth++;
    else if (c === ')') depth = Math.max(0, depth - 1);
    else if (c === ',' && depth === 0) {
      parts.push(body.slice(start, i));
      start = i + 1;
    }
  }
  parts.push(body.slice(start));
  return parts;
}

function rewriteLimitOffset(sql: string): string {
  // LIMIT n OFFSET m
  sql = sql.replace(/\s+LIMIT\s+(\d+)\s+OFFSET\s+(\d+)\s*$/i, ' OFFSET $2 ROWS FETCH FIRST $1 ROWS ONLY');
  // OFFSET m LIMIT n
  sql = sql.replace(/\s+OFFSET\s+(\d+)\s+LIMIT\s+(\d+)\s*$/i, ' OFFSET $1 ROWS FETCH FIRST $2 ROWS ONLY');
  // LIMIT n
  sql = sql.replace(/\s+LIMIT\s+(\d+)\s*$/i, ' FETCH FIRST $1 ROWS ONLY');
  // OFFSET m
  sql = sql.replace(/\s+OFFSET\s+(\d+)\s*$/i, ' OFFSET $1 ROWS');
  return sql;
}

function rewritePgFunctions(sql: string): string {
  return sql
    .replace(/\bcurrent_schema\s*\(\s*\)/gi, 'CURRENT SCHEMA')
    .replace(/\bnow\s*\(\s*\)/gi, 'CURRENT TIMESTAMP')
    .replace(/\bcurrent_date\s*\(\s*\)/gi, 'CURRENT DATE')
    .replace(/\bcurrent_time\s*\(\s*\)/gi, 'CURRENT TIME')
    .replace(/\btrue\b/gi, 'TRUE')
    .replace(/\bfalse\b/gi, 'FALSE');
}


function ensureDb2SelectSource(sql: string): string {
  if (!/^\s*select\b/i.test(sql)) return sql;
  if (hasTopLevelKeyword(sql, 'from')) return sql;
  if (hasTopLevelKeyword(sql, 'union')) return sql;

  // PostgreSQL permits SELECT <expression> without FROM. Db2 for i requires
  // a row source for many such expressions. SYSIBM.SYSDUMMY1 is the canonical
  // one-row compatibility source and preserves PostgreSQL scalar semantics.
  const clauses = ['where', 'group', 'having', 'order', 'offset', 'fetch'];
  let insertion = sql.length;
  for (const clause of clauses) {
    const pos = topLevelKeywordIndex(sql, clause);
    if (pos >= 0 && pos < insertion) insertion = pos;
  }
  const head = sql.slice(0, insertion).trimEnd();
  const tail = sql.slice(insertion);
  return `${head} FROM SYSIBM.SYSDUMMY1${tail ? ` ${tail.trimStart()}` : ''}`;
}

function hasTopLevelKeyword(sql: string, word: string): boolean {
  return topLevelKeywordIndex(sql, word) >= 0;
}

function topLevelKeywordIndex(sql: string, word: string): number {
  let depth = 0;
  let inSingle = false;
  let inDouble = false;
  for (let i = 0; i < sql.length; i++) {
    const c = sql[i]!;
    if (c === "'" && !inDouble) {
      if (inSingle && sql[i + 1] === "'") { i++; continue; }
      inSingle = !inSingle;
      continue;
    }
    if (c === '"' && !inSingle) {
      if (inDouble && sql[i + 1] === '"') { i++; continue; }
      inDouble = !inDouble;
      continue;
    }
    if (inSingle || inDouble) continue;
    if (c === '(') { depth++; continue; }
    if (c === ')') { depth = Math.max(0, depth - 1); continue; }
    if (depth !== 0) continue;
    if (sql.slice(i, i + word.length).toLowerCase() !== word) continue;
    const before = i === 0 ? '' : sql[i - 1]!;
    const after = sql[i + word.length] ?? '';
    if (!/[A-Za-z0-9_$]/.test(before) && !/[A-Za-z0-9_$]/.test(after)) return i;
  }
  return -1;
}

function rewriteInformationSchema(sql: string): string {
  return sql
    .replace(/\binformation_schema\.tables\b/gi, 'SYSIBM.TABLES')
    .replace(/\binformation_schema\.columns\b/gi, 'SYSIBM.COLUMNS')
    .replace(/\binformation_schema\.schemata\b/gi, 'SYSIBM.SCHEMATA');
}

function rewritePgCatalog(sql: string): string {
  const namespaces = `(SELECT 50000 + ROW_NUMBER() OVER (ORDER BY SCHEMA_NAME) AS oid, SCHEMA_NAME AS nspname FROM QSYS2.SYSSCHEMAS)`;
  const classes = `(SELECT 100000 + ROW_NUMBER() OVER (ORDER BY TABLE_SCHEMA, TABLE_NAME) AS oid, TABLE_NAME AS relname, 50000 + (SELECT COUNT(*) FROM QSYS2.SYSSCHEMAS N WHERE N.SCHEMA_NAME <= T.TABLE_SCHEMA) AS relnamespace, CASE WHEN TABLE_TYPE='V' THEN 'v' WHEN TABLE_TYPE='M' THEN 'm' ELSE 'r' END AS relkind, 0 AS reltuples FROM QSYS2.SYSTABLES T)`;
  return sql
    .replace(/\bpg_catalog\.pg_namespace\b/gi, namespaces)
    .replace(/(?<![A-Za-z0-9_.])pg_namespace\b/gi, namespaces)
    .replace(/\bpg_catalog\.pg_class\b/gi, classes)
    .replace(/(?<![A-Za-z0-9_.])pg_class\b/gi, classes);
}

function uppercaseUnquotedRelationIdentifiers(sql: string): string {
  // IBM i SQL naming is case-insensitive for unquoted identifiers. This targeted
  // normalizer avoids altering string literals and quoted identifiers.
  const chars = [...sql];
  let inSingle = false, inDouble = false;
  for (let i = 0; i < chars.length; i++) {
    if (chars[i] === "'" && !inDouble) {
      if (inSingle && chars[i + 1] === "'") { i++; continue; }
      inSingle = !inSingle; continue;
    }
    if (chars[i] === '"' && !inSingle) { inDouble = !inDouble; continue; }
    if (!inSingle && !inDouble && /[a-z]/.test(chars[i]!)) chars[i] = chars[i]!.toUpperCase();
  }
  return chars.join('');
}

function hasMultipleStatements(sql: string): boolean {
  let inSingle = false, inDouble = false;
  let semicolons = 0;
  for (let i = 0; i < sql.length; i++) {
    const c = sql[i];
    if (c === "'" && !inDouble) {
      if (inSingle && sql[i + 1] === "'") { i++; continue; }
      inSingle = !inSingle;
    } else if (c === '"' && !inSingle) inDouble = !inDouble;
    else if (c === ';' && !inSingle && !inDouble) semicolons++;
  }
  return semicolons > 1 || (semicolons === 1 && !/;\s*$/.test(sql));
}
